appname: denti
port: 8282
logger:
    use: zapLogger
    environment: dev
    loglevel: debug
    filename: denti.log
db:
    use: mysql
    postgres:
        enabled: true
        host: localhost
        port: 5432
        username: postgres
        password: postgres
        database: denti
    mysql:
        enabled: true
        host: localhost
        port: 3306
        username: root
        password: 12345678
        database: denti
contacts:
    name: 'Akbar Shaikh'
    email: aashaikh55@gmail.com
